name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: docker://pandoc/core:3.8
        with:
          args: "--help" # gets appended to pandoc command
